version: "3"
services:
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=server
      - POSTGRES_DB=server
    ports:
      - "6432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:
